"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from pathlib import Path  # noqa: F401 # pylint: disable=W0611
from typing import Optional, Union  # noqa: F401 # pylint: disable=W0611

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


def query_string() -> str:
    with open(f"{Path(__file__).parent}/cloudflare_zones.gql", "r") as f:
        return f.read()


class CloudflareAccountV1(BaseModel):
    name: str = Field(..., alias="name")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareZoneV1(BaseModel):
    account: CloudflareAccountV1 = Field(..., alias="account")
    name: str = Field(..., alias="name")
    plan: Optional[str] = Field(..., alias="plan")
    q_type: Optional[str] = Field(..., alias="type")
    settings: Optional[Json] = Field(..., alias="settings")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareZonesQueryData(BaseModel):
    zones: Optional[list[CloudflareZoneV1]] = Field(..., alias="zones")

    class Config:
        smart_union = True
        extra = Extra.forbid
