"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from pathlib import Path  # noqa: F401 # pylint: disable=W0611
from typing import Optional, Union  # noqa: F401 # pylint: disable=W0611

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


def query_string() -> str:
    with open(f"{Path(__file__).parent}/cloudflare_accounts.gql", "r") as f:
        return f.read()


class VaultSecretV1(BaseModel):
    path: str = Field(..., alias="path")
    field: str = Field(..., alias="field")

    class Config:
        smart_union = True
        extra = Extra.forbid


class AWSAccountV1_VaultSecretV1(BaseModel):
    path: str = Field(..., alias="path")
    field: str = Field(..., alias="field")

    class Config:
        smart_union = True
        extra = Extra.forbid


class AWSTerraformStateIntegrationsV1(BaseModel):
    integration: str = Field(..., alias="integration")
    key: str = Field(..., alias="key")

    class Config:
        smart_union = True
        extra = Extra.forbid


class TerraformStateAWSV1(BaseModel):
    provider: str = Field(..., alias="provider")
    bucket: str = Field(..., alias="bucket")
    region: str = Field(..., alias="region")
    integrations: Optional[list[AWSTerraformStateIntegrationsV1]] = Field(
        ..., alias="integrations"
    )

    class Config:
        smart_union = True
        extra = Extra.forbid


class AWSAccountV1(BaseModel):
    name: str = Field(..., alias="name")
    automation_token: AWSAccountV1_VaultSecretV1 = Field(..., alias="automationToken")
    terraform_state: Optional[TerraformStateAWSV1] = Field(..., alias="terraformState")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareAccountV1(BaseModel):
    name: str = Field(..., alias="name")
    provider_version: str = Field(..., alias="providerVersion")
    enable_deletion: Optional[bool] = Field(..., alias="enableDeletion")
    api_credentials: VaultSecretV1 = Field(..., alias="apiCredentials")
    terraform_state_account: AWSAccountV1 = Field(..., alias="terraformStateAccount")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareAccountsQueryData(BaseModel):
    accounts: Optional[list[CloudflareAccountV1]] = Field(..., alias="accounts")

    class Config:
        smart_union = True
        extra = Extra.forbid
