"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from pathlib import Path  # noqa: F401 # pylint: disable=W0611
from typing import Optional, Union  # noqa: F401 # pylint: disable=W0611

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


def query_string() -> str:
    with open(f"{Path(__file__).parent}/cloudflare_records.gql", "r") as f:
        return f.read()


class CloudflareAccountV1(BaseModel):
    name: str = Field(..., alias="name")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareZoneV1(BaseModel):
    name: str = Field(..., alias="name")
    account: CloudflareAccountV1 = Field(..., alias="account")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareRecordV1(BaseModel):
    zone: CloudflareZoneV1 = Field(..., alias="zone")
    name: str = Field(..., alias="name")
    q_type: str = Field(..., alias="type")
    ttl: int = Field(..., alias="ttl")
    value: str = Field(..., alias="value")
    proxied: Optional[bool] = Field(..., alias="proxied")

    class Config:
        smart_union = True
        extra = Extra.forbid


class CloudflareRecordsQueryData(BaseModel):
    records: Optional[list[CloudflareRecordV1]] = Field(..., alias="records")

    class Config:
        smart_union = True
        extra = Extra.forbid
